name: CI

on: [push]

jobs:
  linux-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd wheel
        if [ `python --version 2>&1 | cut -c8` == "2" ]; then
          pip install peak_engines-*-cp27-cp27mu-manylinux1_x86_64.whl
        else
          pip install peak_engines-*-cp32-abi3-manylinux1_x86_64.whl
        fi
        pip install scikit-learn
        pip install scipy
    - name: Test Warped Linear Regression
      run: |
        python test/warped_linear_regression_test.py
    - name: Test Ridge Regression
      run: |
        python test/ridge_regression_test.py
    - name: Test Logistic Regression
      run: |
        python test/logistic_regression_test.py

  osx-python:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd wheel
        if [ `python --version 2>&1 | cut -c8` == "2" ]; then
          pip install peak_engines-*-cp27-cp27m-macosx_10_9_intel.whl
        else
          pip install peak_engines-*-cp32-abi3-macosx_10_9_intel.whl
        fi
        pip install scikit-learn
        pip install scipy
    - name: Test Warped Linear Regression
      run: |
        python test/warped_linear_regression_test.py
    - name: Test Ridge Regression
      run: |
        python test/ridge_regression_test.py
    - name: Test Logistic Regression
      run: |
        python test/logistic_regression_test.py

  linux-r:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get install --no-install-recommends --no-install-suggests -y \
                r-base r-cran-glmnet
        R CMD INSTALL packge/PeakEngines-linux-*
    - name: Test Ridge Regression
      run: |
        echo
    - name: Test Logistic Regression
      run: |
        echo
