name: CI

on: [push]

jobs:
  linux-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd wheel
        if [ `python --version 2>&1 | cut -c8` == "2" ]; then
          pip install peak_engines-*-manylinux1_x86_64.whl
        else
          pip install peak_engines-*-manylinux1_x86_64.whl
        fi
        pip install pytest
        pip install scikit-learn
        pip install scipy
    - name: Test Ridge Regression
      run: |
        python test/ridge_regression_test.py
    - name: Test Logistic Regression
      run: |
        python test/binary_logistic_regression_test.py
    - name: Test Multinomial Logistic Regression
      run: |
        python test/multinomial_logistic_regression_test.py

  osx-python:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd wheel
        if [ `python --version 2>&1 | cut -c8` == "2" ]; then
          pip install peak_engines-*-macosx_10_9_intel.whl
        else
          pip install peak_engines-*-macosx_10_9_intel.whl
        fi
        pip install pytest
        pip install scikit-learn
        pip install scipy
    - name: Test Ridge Regression
      run: |
        python test/ridge_regression_test.py
    - name: Test Logistic Regression
      run: |
        python test/binary_logistic_regression_test.py
    - name: Test Multinomial Logistic Regression
      run: |
        python test/multinomial_logistic_regression_test.py
