name: Python package

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd wheel
        if [ `python --version 2>&1 | cut -c8` == "2" ]; then
          pip install peak_engines-*-cp27-cp27mu-manylinux1_x86_64.whl
        else
          pip install peak_engines-*-cp32-abi3-manylinux1_x86_64.whl
        fi
    - name: Test
      run: |
        python test.py
        python test/ridge_regression_test.py

  osx:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd wheel
        if [ `python --version 2>&1 | cut -c8` == "2" ]; then
          pip install peak_engines-*-cp27-cp27m-macosx_10_9_intel.whl
        else
          pip install peak_engines-*-cp32-abi3-macosx_10_9_intel.whl
        fi
    - name: Test
      run: |
        python test.py
        python test/ridge_regression_test.py
