name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ `python --version 2>&1 | cut -c8` == "2" ]; then
          pip install wheel/peak_engines-0.1.0-cp27-cp27mu-manylinux1_x86_64.whl
        else
          pip install wheel/peak_engines-0.1.0-cp32-abi3-manylinux1_x86_64.whl
        fi
    - name: Test with pytest
      run: |
        pytest
